- hosts: all
  tasks:
   	- name: stop container
    	shell: docker container stop greenhost
 	  - name: remove container
    	shell: docker container rm greenhost
 	  - name: remove docker image
    	shell: docker image rm 959597/greenhost
 	  - name: create container
   	  shell: docker container run -itd --name greenhost -p 9000:80 959597/greenhost
