- hosts: dockerhost
  tasks:
    - name: remove docker image
      shell: docker image rm 959597/mygreenhost
    - name: create container
      shell: docker container run -itd --name mygreenhostall -p 9000:80 959597/mygreenhost

